# Project information
site_name: ElementEmbeddings
site_url: https://wmd-group.github.io/ElementEmbeddings/
site_author: Anthony Onwuli

# Repository
repo_url: https://github.com/WMD-group/ElementEmbeddings
repo_name: 'ElementEmbeddings'
edit_uri: ""

nav:
    - Home: index.md
    - About: about.md
    - Getting Started: installation.md
    - 'Python package':
      - 'Core module': 'python_api/core.md'
      - 'Composition module': 'python_api/composition.md'
      - 'Plotter module': 'python_api/plotter.md'
    - Tutorial: tutorials.md
    - reference.md
    - Contributing: contribution.md
    - Issue Tracker: https://github.com/WMD-group/ElementEmbeddings/issues

# Configuration
theme:
  name: material
  custom_dir: docs/.overrides


# Customisation
extra:
  version:
    provider: mike


plugins:
    - mkdocstrings
    - search
    - autorefs



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

# Configuration

